### ISSUE TITLE
Build with Font Awesome Pro: missing duotone.js

### ISSUE THREAD

**Issue by AndrasJanurik** [FlowingCode/FontAwesomeIronIconset#85]
Hi,

I am coming from #83 and there is a new error so I thought it is probably a new issue.
But please check out my last comment on #83 as well because the aliases.xml and the the demo files problem might interest you.

The next problem is when using the the new font awesome pro jar file I get a maven build error:

```
Could not execute build-frontend goal: Error occured during goal execution: 
 
   Failed to find the following files: 
       - ./font-awesome-duotone/duotone.js
   
   Locations searched were:
       - `...\frontend` in this project
       - `META-INF/frontend` in included JARs
       - `META-INF/resources/frontend` in included JARs
 
   Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
 ```

Or when trying to run it from eclipse it gives the following additional stack trace for the same error:
```
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getUniqueEs6ImportPaths(AbstractUpdateImports.java:400) ~[flow-server-23.3.2.jar:23.3.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getModuleLines(AbstractUpdateImports.java:413) ~[flow-server-23.3.2.jar:23.3.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.collectModules(AbstractUpdateImports.java:324) ~[flow-server-23.3.2.jar:23.3.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:128) ~[flow-server-23.3.2.jar:23.3.2]
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:396) ~[flow-server-23.3.2.jar:23.3.2]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:342) ~[flow-server-23.3.2.jar:23.3.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:435) ~[vaadin-dev-server-23.3.2.jar:?]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:348) ~[vaadin-dev-server-23.3.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

```

I checked and the jar really doesn't contain the file.
The contents of the META-INF\resources\frontend folder:
```
\---frontend
    \---font-awesome-iron-iconset
            fab.js
            fad.js
            fal.js
            far.js
            fas.js

```

The contents of the META-INF\resources\frontend folder of your standard jar:
```
\---frontend
    +---font-awesome-duotone
    |       duotone.js
    |       
    \---font-awesome-iron-iconset
            fab.js
            far.js
            fas.js

```

Is this a build problem?
Can you please help?

**Comment by AndrasJanurik** [comment]
Hi, do you think you can fix this anytime soon?

**Comment by javier-godoy** [comment]
Hello. `duotone.js` should be included in the jar, but I don't have FontAwesome Pro at the moment. (We developed the integration for a customer a while ago; and maybe we inadvertently broke the build process in some release). If you can share a private repository with your setup, I can take a look.

**Comment by AndrasJanurik** [comment]
Hi. In #83 I already posted a file list of my FontAwesome Pro zip file, but I can post it here as well.
Please let mw know if that is what you need.
[pro_package_file_list.txt](https://github.com/FlowingCode/FontAwesomeIronIconset/files/11615088/pro_package_file_list.txt)

**Comment by mlopezFC** [comment]
Can you supply a complete sample project that is able to reproduce the issue easily? What we would need is something like a zip file with a project that you download, unzip and start the application and then some simple steps to reproduce the problem. 
In your case maybe you could supply some fake icons instead of the pro icons of course.
Thanks!
